package org.apache.tapestry5.csrfprotection.tests.auto;

import java.util.List;

import org.apache.tapestry5.csrfprotection.services.CsrfProtectionModule;
import org.apache.tapestry5.csrfprotection.tests.auto.services.AppModule;
import org.apache.tapestry5.dom.Document;
import org.apache.tapestry5.dom.Element;
import org.apache.tapestry5.test.PageTester;
import org.jaxen.JaxenException;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.formos.tapestry.xpath.TapestryXPath;

/**
 * Simulates a CSRF attack against the created event links of the AjaxFormLoop component.
 */
public class AjaxFormLoopAttackTest extends Assert
{

    /**
     * Sends the request generated by the RemoveRowLink component without anti CSRF parameter.
     */
    @Test
    public void testAttackRemoveRowLink()
    {
        String appPackage = "org.apache.tapestry5.csrfprotection.tests.auto";
        String appName = "AutoMode";
        PageTester tester = new PageTester(appPackage, appName,
            "src/test/webapp", CsrfProtectionModule.class,
            AppModule.class);

        tester.renderPage("AjaxFormLoop");
        org.apache.tapestry5.dom.Document doc = tester.renderPage("AjaxFormLoopAttack");
        List<Element> list;
        try
        {
            list = TapestryXPath.xpath("id('removeRowLink')").selectElements(doc);
            assertTrue(list.size() == 1,
                "There should be only one link with id removeRowLink");
            Element actionLink = list.get(0);
            Document response = tester.clickLink(actionLink);
            assertTrue(response.toString().contains("CSRF Attack detected"));
        }
        catch (JaxenException e)
        {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    /**
     * Sends the request generated by the AddRowLink component without the anti CSRF parameter.
     */
    @Test
    public void testAttackAddRowLink()
    {
        String appPackage = "org.apache.tapestry5.csrfprotection.tests.auto";
        String appName = "AutoMode";
        PageTester tester = new PageTester(appPackage, appName,
            "src/test/webapp", CsrfProtectionModule.class,
            AppModule.class);

        tester.renderPage("AjaxFormLoop");
        org.apache.tapestry5.dom.Document doc = tester.renderPage("AjaxFormLoopAttack");
        List<Element> list;
        try
        {
            list = TapestryXPath.xpath("id('addRowLink')").selectElements(doc);
            assertTrue(list.size() == 1,
                "There should be only one link with id removeRowLink");
            Element actionLink = list.get(0);
            Document response = tester.clickLink(actionLink);
            assertTrue(response.toString().contains("CSRF Attack detected"));
        }
        catch (JaxenException e)
        {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
